  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/posts/"
  
  [[main]]
  name = "Tags"
  weight = 300
  identifier = "tags"
  url = "/tags/"

  [[main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"
