
title = "Jason Meridth"
author = "Jason Meridth"
description = "Learn, Converse, Share"
displayMode = "light"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = [] 
mainSections = ["posts"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
singleDateFormat = "1/2/2006"
indexDateFormat = "1/2/2006"
listDateFormat = "1/2/2006"
readMore = true

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/jmeridth"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/jmeridth"

[[socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://twitter.com/jmeridth"

[[socialIcons]]
icon = "fas fa-file"
title = "resume"
url = "https://tinyurl.com/meridthresume"

[[socialIcons]]
icon = "fas fa-envelope"
title = "email"
url = "mailto:jmeridth@gmail.com"
