DirectoryIndex: "index.html"
DirectoryPath: "public"
EnforceHTTPS: false
CheckInternalHash: false
IgnoreDirectoryMissingTrailingSlash: true
IgnoreURLs:
  - "^/index\\.html$"
  - "index\\.xml"
  # Placeholder/example URLs in tutorial content
  - "www\\.server\\.com"
  - "mydomain"
  - "127\\.0\\.0\\.1"
  - "123\\.123\\.123\\.123"
  # Dead domains (DNS failures)
  - "www\\.edreaminghome\\.com"
  - "codebetter\\.com"
  - "codemonkey\\.nmonta\\.com"
  - "blog\\.agilejoe\\.com"
  - "adnug\\.com"
  - "agilejoe\\.lostechies\\.com"
  - "ajepst\\.devlicio\\.us"
  - "api\\.castleproject\\.org"
  - "blog\\.devjavu\\.com"
  - "blog\\.qoqoa\\.com"
  - "blogs\\.dovetailsoftware\\.com"
  - "boo\\.codehaus\\.org"
  - "chadmyers\\.lostechies\\.com"
  - "cheat\\.errtheblog\\.com"
  - "colinjack\\.lostechies\\.com"
  - "confluence\\.public\\.thoughtworks\\.org"
  - "derickbailey\\.lostechies\\.com"
  - "go4webapps\\.com"
  - "images\\.bestwebbuys\\.com"
  - "jason\\.lostechies\\.com"
  - "jimmybogard\\.lostechies\\.com"
  - "joeybeninghove\\.lostechies\\.com"
  - "joeydotnet\\.com"
  - "joshuaflanagan\\.lostechies\\.com"
  - "linux\\.about\\.com"
  - "projects\\.wh\\.techno-weenie\\.net"
  - "rails\\.vim\\.tpope\\.net"
  - "rhouston\\.lostechies\\.com"
  - "schacon\\.github\\.com"
  - "schambers\\.lostechies\\.com"
  - "skillsmatter\\.com"
  - "static\\.rubiverse\\.com"
  - "tech\\.groups\\.yahoo\\.com"
  - "transfers\\.one\\.microsoft\\.com"
  - "tryruby\\.hobix\\.com"
  - "us\\.accessories\\.skype\\.com"
  - "using\\.castleproject\\.org"
  - "www\\.bishopmeridth\\.com"
  - "www\\.chrisbrandsma\\.com"
  - "www\\.cifactory\\.org"
  - "www\\.connectu\\.com"
  - "www\\.csd\\.toshiba\\.com"
  - "www\\.devcares\\.com"
  - "www\\.drdobbs\\.com"
  - "www\\.elluminate\\.com"
  - "www\\.flux88\\.com"
  - "flux88\\.com"
  - "www\\.foldershare\\.com"
  - "www\\.io\\.com"
  - "www\\.joeydotnet\\.com"
  - "www\\.jpboodhoo\\.com"
  - "www\\.okcodecamp\\.com"
  - "www\\.okcpro\\.net"
  - "www\\.pec\\.stedwards\\.edu"
  - "www\\.visualstudioisland\\.com"
  - "www\\.tetlaw\\.id\\.au"
  - "www\\.pragprog\\.com"
  - "pragprog\\.com"
  - "gitorious\\.com"
  - "studios\\.thoughtworks\\.com"
  - "cinnamon\\.linuxmint\\.com"
  - "geekswithblogs\\.net"
  - "sternisha\\.com"
  - "release\\.seleniumhq\\.org"
  - "media\\.rubyonrails\\.org"
  - "www\\.cifactory\\.org"
  # Alive domains where all referenced pages are gone (404)
  - "benscheirman\\.com"
  - "castleproject\\.org"
  - "builds\\.castleproject\\.org"
  - "colinramsay\\.co\\.uk"
  - "book\\.git-scm\\.com"
  - "weblogs\\.asp\\.net"
  - "blogs\\.msdn\\.com"
  - "www\\.webhost4life\\.com"
  - "www\\.codeproject\\.com"
  - "bp\\.blogspot\\.com"
  - "www\\.ayende\\.com"
  - "devlicious\\.com"
  - "www\\.jasonmeridth\\.com"
  # Domains that timeout consistently
  - "ankhsvn\\.tigris\\.org"
  - "storyteller\\.tigris\\.org"
  - "articles\\.slicehost\\.com"
  - "slicehost\\.com"
  - "davidhayden\\.com"
  - "davidkean\\.net"
  - "devlicio\\.us"
  - "hammett\\.castleproject\\.org"
  - "mechanicalrobotfish\\.com"
  - "subversion\\.tigris\\.org"
  - "www\\.agile-tools\\.net"
  - "www\\.dotnetkicks\\.com"
  - "www\\.gotdotnet\\.com"
  - "www\\.kiwidude\\.com"
  - "www\\.lostechies\\.com"
  - "www\\.twhirl\\.org"
  - "hudson\\.dev\\.java\\.net"
  - "hudson\\.gotdns\\.com"
  - "www\\.clicktoattend\\.com"
  - "www\\.houstontechfest\\.com"
  - "www\\.reviewlinux\\.com"
  - "www\\.awprofessional\\.com"
  - "oneplus\\.net"
  - "islandlinux\\.org"
  - "water\\.usgs\\.gov"
  # Twitter/X returns 520 for old URLs
  - "twitter\\.com"
  - "www\\.twitter\\.com"
  # Old relative image paths from WordPress migration
  - "blogs/jason_meridth/WindowsLiveWriter"
  - "jasonmeridth/files/"
  - "blogs/jason_meridth/"
  - "blogs/chad_myers/"
  - "blogs/sean_chambers/"
  - "blogs/joe_ocampo/"
  - "blogs/nelson_montalvo/"
  # Old WordPress controlpanel paths
  - "/controlpanel/"
  # Hugo template variable leak
  - "%7B%7Bsite\\.url%7D%7D"
  # Localhost URLs (example/tutorial content)
  - "localhost"
  - "raw\\.githubusercontent\\.com\\/nblock\\/pdb-cheatsheet\\/master\\/pdb-cheatsheet\\.png"
IgnoreDirs:
  - "lib"
IgnoreAltMissing: true
CacheExpires: "6h"
