BaseURL = "http://blog.jasonmeridth.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "Jason Meridth"
title = "JM (Jason Meridth)"
theme = "vitae"
paginate = 5
enableRobotsTXT = true
enableGitInfo = true

copyright = "© Copyright notice | [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[markup]
  [markup.highlight]
    codeFences = true
    noClasses = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    style = "monokai"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
	darkmode = false
	homepage = false
	keywords = ["jason meridth","meridth","jm","software developer"]
	description = "I am a continuously learning software developer trying to not let best be the enemy of better."
	pagetitle = "Learn, Converse, Share"
	subtitle = "Learn, Converse, Share"
	math = true
	avatar = "/img/jmavatar.jpeg"
	favicon = true
	mainSections = ["posts"]
	readingTime = true
	wordCount = true
	hideAuthor = true

[params.customjs]
enabled = false

[params.comments]
enabled = false

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 5

# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/jmeridth"

[[params.social]]
name = "Email"
icon = "fas fa-envelope"
cmd = "mailto:jmeridth@gmail.com"

[[params.social]]
name = "LinkedIn"
icon = "fab fa-linkedin"
url = "https://linkedin.com/in/jmeridth"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"
