BaseURL = "http://blog.jasonmeridth.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "Jason Meridth"
title = "Jason Meridth"
theme = "vitae"
paginate = 5
enableRobotsTXT = true

copyright = "© Copyright notice | [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
	# Enable dark mode as default
	darkmode = false

	# Use homepage.md instead of a list of posts
	homepage = false

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = ["jason meridth","meridth","jm","software developer"]

	# Add meta description in head part
	description = "I am a continuously learning software developer trying to not let best be the enemy of better."

	# Add pagetitle to homepage <title> tag
	pagetitle = "Learn, Converse, Share"

	# Add a subtitle to your website
	subtitle = "Learn, Converse, Share"

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Optional 80x80 avatar image.
	avatar = "/img/avatar.jpg"

	# Optional favicons for website
	favicon = true

	# Add list of sections that should show up on the homepage
	mainSections = ["posts"]

	# Add list of Sections/Types that should no be considered by RSS
	#nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Custom CSS applied to default styles. (Path could be "static/css/")
	#customcss = "css/custom.css"

	# Show reading time on a post
	readingTime = true

	# Show word count on a post
	wordCount = true

	# Show author on a post (groups with readingTime and wordCount)
	hideAuthor = true

# Custom JavaScript
[params.customjs]
# enable Javascript by setting to true
enabled = false

# add a filepath (could be "static/js/")
#src = "js/main.js"

# specifies which referrer information to send when fetching the script
#referrerpolicy = "no-referrer"

# specifies that the script should not be executed in browsers supporting ES2015 modules
#nomodule = false

# Allows a browser to check for integrity to ensure the code hasn't been manipulated
#integrity= ""

# execute the script when page has finished parsing (external only)
#defer = true

# sets the mode of the request to an http cors request
#crossorigin=true

# executes the script asynchronously (external only)
#async = true

# Comments
[params.comments]
# Enable Comments with "true"
enabled = false

# Comment provider:
#   disqus (https://disqus.com)
#   commento (https://commento.io)
#engine = "disqus"

# Content types to disable comments on.
#disableOnTypes = ["page"]

[params.comments.disqus]
#shortname = "" # Paste the shortname from your Disqus dashboard.

[params.comments.commento]
#host = "" # Paste the domain of you commento.io system

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 5

# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/jmeridth"

[[params.social]]
name = "Email"
icon = "fas fa-envelope"
cmd = "mailto:jmeridth@gmail.com"

[[params.social]]
name = "LinkedIn"
icon = "fab fa-linkedin"
url = "https://linkedin.com/in/jmeridth"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"
