issuer: https://token.actions.githubusercontent.com
subject_pattern: "repo:jmeridth/jmeridth.github.io:(pull_request|ref:refs/heads/.+)"
claim_pattern:
  job_workflow_ref: "^jmeridth/jmeridth.github.io/.github/workflows/osps-security-assessment.yaml@refs/(heads/.+|pull/[0-9]+/merge)$"

permissions:
  contents: read
  statuses: read
  deployments: read
  security_events: read
  administration: read
