---
name: Auto Labeler
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    permissions:
      contents: read # Required by reusable workflow
      pull-requests: write # Apply labels to PRs
    uses: github-community-projects/ospo-reusable-workflows/.github/workflows/auto-labeler.yaml@7fc8753b3666b929250bb6241ce4b2d35f316a11
    with:
      config-name: release-drafter.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
