---
name: Verify Links and Images

on:
  pull_request:
    paths:
      - content/posts/**
  workflow_run:
    workflows: ["github pages"]
    types:
      - completed
  workflow_dispatch:

jobs:
  htmltest:
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag v6.0.2
        with:
          submodules: true
          fetch-depth: 0
          persist-credentials: false

      - name: Get changed posts
        id: changed-posts
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # tag v47.0.5
        with:
          files: content/posts/**

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # tag v3.0.0
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify

      - name: Verify links and images
        if: steps.changed-posts.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_run'
        uses: wjdp/htmltest-action@31be84a95c860a331e0cf9a99f71e3eb39d2f86b
        with:
          config: .htmltest.yml
