## Reference: https://github.com/amannn/action-semantic-pull-request
---
name: "Lint PR Title"
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    permissions:
      contents: read # Required by reusable workflow
      pull-requests: read # Read PR title
      statuses: write # Report lint status
    uses: github-community-projects/ospo-reusable-workflows/.github/workflows/pr-title.yaml@6d7a83e6fc8275128984b0ed3defa4b8cdc40f85
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
