---
name: Release Handler

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  main:
    permissions:
      contents: write
      pull-requests: write
    name: Generate release notes
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          config-name: release-drafter.yml
          publish: true
